aruco_wrapper:
  boxes:
    fiducial_0:
      size: [0.3, 0.2, 0.2]
      center: [0, 0, -0.1]

    fiducial_1:
      size: [2.0, 0.76, 0.4]
      center: [0, 0.30, -0.255]

  grasp:
    arm1_8: 
      base_frame: fiducial_0
      offset: [0.30, 0, 0.0]
    arm2_8: 
      base_frame: fiducial_0
      offset: [-0.30, 0, 0.0]

validity_check:
  planning_scene:
    padding: 0.03